import { Listing, Inquiry, Comment, Conversation, WalletTransaction } from "./types";

export const listings: Listing[] = [
  {
    id: "1",
    title: "2019 Toyota Corolla – Low Mileage",
    description:
      "Well-maintained 2019 Toyota Corolla in excellent condition. Single owner, full service history, factory tint, push-start, reverse camera. Never in an accident. Registered and insured. Available for viewing in Maraval.",
    price: 185000,
    currency: "TTD",
    category: "Vehicles",
    condition: "Like New",
    location: "Maraval, Port of Spain",
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    ],
    seller: {
      id: "s1",
      name: "Marcus Phillip",
      avatar: "https://i.pravatar.cc/80?img=11",
      joinedDate: "2022-03-14",
      rating: 4.8,
      reviewCount: 23,
      location: "Port of Spain",
      verified: true,
      isPro: false,
    },
    createdAt: "2026-05-28",
    featured: true,
    tier: "featured",
    tags: ["toyota", "sedan", "automatic", "fuel-efficient"],
    negotiable: true,
    commentCount: 4,
  },
  {
    id: "2",
    title: "MacBook Pro 14\" M3 – Space Grey",
    description:
      "Barely used MacBook Pro 14-inch with M3 chip, 16GB RAM, 512GB SSD. Purchased 4 months ago, still under Apple warranty. Comes with original box, charger, and AppleCare+. No scratches.",
    price: 9800,
    currency: "TTD",
    category: "Electronics",
    condition: "Like New",
    location: "San Fernando",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
      "https://images.unsplash.com/photo-1611186871525-9c7d31db1359?w=800&q=80",
    ],
    seller: {
      id: "s2",
      name: "Priya Ramlal",
      avatar: "https://i.pravatar.cc/80?img=5",
      joinedDate: "2021-09-02",
      rating: 5.0,
      reviewCount: 41,
      location: "San Fernando",
      verified: true,
      isPro: true,
      businessName: "Priya Tech Deals",
      bio: "Certified Apple reseller and tech enthusiast. All items verified, tested, and honestly described.",
      banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80",
      listingCount: 12,
    },
    createdAt: "2026-06-01",
    featured: true,
    tier: "premium",
    tags: ["apple", "laptop", "m3", "programming"],
    negotiable: false,
    commentCount: 7,
  },
  {
    id: "3",
    title: "3-Bedroom House for Rent – Chaguanas",
    description:
      "Spacious 3-bedroom, 2-bathroom house in a quiet residential area of Chaguanas. Fully tiled, security grilles on all windows, covered parking for 2 cars. Close to schools and shopping centres. Available August 1st.",
    price: 5500,
    currency: "TTD",
    category: "Real Estate",
    condition: "New",
    location: "Chaguanas",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ],
    seller: {
      id: "s3",
      name: "Anita Mohammed",
      avatar: "https://i.pravatar.cc/80?img=47",
      joinedDate: "2020-01-15",
      rating: 4.6,
      reviewCount: 17,
      location: "Chaguanas",
      verified: true,
      isPro: true,
      businessName: "Anita Real Estate",
      bio: "Licensed real estate agent covering Central Trinidad. Residential and commercial properties.",
      banner: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80",
      listingCount: 8,
    },
    createdAt: "2026-05-20",
    featured: true,
    tier: "premium",
    tags: ["rental", "house", "chaguanas", "family"],
    negotiable: true,
    commentCount: 2,
  },
  {
    id: "4",
    title: "Homemade Black Cake – Order for Events",
    description:
      "Traditional Trinidad black cake made with dried fruits soaked in rum and cherry brandy. Perfect for weddings, christenings, and the holiday season. Customisable sizes. Order minimum 2 weeks in advance.",
    price: 350,
    currency: "TTD",
    category: "Food & Beverage",
    condition: "New",
    location: "Arima",
    images: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80",
    ],
    seller: {
      id: "s4",
      name: "Cheryl James",
      avatar: "https://i.pravatar.cc/80?img=32",
      joinedDate: "2023-06-10",
      rating: 4.9,
      reviewCount: 88,
      location: "Arima",
      verified: false,
      isPro: false,
    },
    createdAt: "2026-06-05",
    featured: false,
    tier: "free",
    tags: ["cake", "baking", "events", "traditional"],
    negotiable: false,
    commentCount: 11,
  },
  {
    id: "5",
    title: "Professional AC Installation & Repair",
    description:
      "Certified HVAC technician with 12 years experience. We install, service, and repair all brands of split-unit and window ACs. Same-day service available across Trinidad. Free quote on WhatsApp.",
    price: 600,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "Tunapuna",
    images: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    ],
    seller: {
      id: "s5",
      name: "Kevin Sookdeo",
      avatar: "https://i.pravatar.cc/80?img=15",
      joinedDate: "2019-11-20",
      rating: 4.7,
      reviewCount: 134,
      location: "Tunapuna",
      verified: true,
      isPro: true,
      businessName: "KoolAir Services",
      bio: "Trusted HVAC contractor since 2010. Serving all of Trinidad with same-day availability.",
      banner: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&q=80",
      listingCount: 5,
    },
    createdAt: "2026-04-18",
    featured: false,
    tier: "featured",
    tags: ["ac", "hvac", "repair", "installation"],
    negotiable: true,
    commentCount: 3,
  },
  {
    id: "6",
    title: "iPhone 15 Pro – 256GB Natural Titanium",
    description:
      "iPhone 15 Pro, 256GB in Natural Titanium. Local carrier unlocked. Screen in perfect condition, no scratches. Comes with original box and one Apple USB-C cable. Battery health 98%.",
    price: 5200,
    currency: "TTD",
    category: "Electronics",
    condition: "Good",
    location: "Couva",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484429be?w=800&q=80",
    ],
    seller: {
      id: "s6",
      name: "Devika Singh",
      avatar: "https://i.pravatar.cc/80?img=49",
      joinedDate: "2024-01-05",
      rating: 4.4,
      reviewCount: 9,
      location: "Couva",
      verified: false,
      isPro: false,
    },
    createdAt: "2026-06-08",
    featured: true,
    tier: "featured",
    tags: ["iphone", "apple", "smartphone", "unlocked"],
    negotiable: true,
    commentCount: 5,
  },
  {
    id: "7",
    title: "Kayak + Paddle Set – Barely Used",
    description:
      "10-foot sit-on-top kayak with adjustable footrests and dry storage compartment. Comes with one paddle and a life vest. Ideal for Caroni, Nariva, or coastal paddling. Selling because we're relocating.",
    price: 2800,
    currency: "TTD",
    category: "Sports & Outdoors",
    condition: "Like New",
    location: "Debe",
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    ],
    seller: {
      id: "s7",
      name: "Tariq Ali",
      avatar: "https://i.pravatar.cc/80?img=12",
      joinedDate: "2022-08-30",
      rating: 4.5,
      reviewCount: 6,
      location: "Debe",
      verified: false,
      isPro: false,
    },
    createdAt: "2026-05-15",
    featured: false,
    tier: "free",
    tags: ["kayak", "outdoor", "water sports", "paddle"],
    negotiable: true,
    commentCount: 1,
  },
  {
    id: "8",
    title: "Designer Wrap Dress – Local Brand",
    description:
      "Hand-sewn wrap dress by Trinidadian designer Sasha Creations. Size M. Cotton/linen blend, perfect for fetes, beach limes, and corporate casual. Washed once, excellent condition. Original price $780 TTD.",
    price: 450,
    currency: "TTD",
    category: "Fashion",
    condition: "Like New",
    location: "Diego Martin",
    images: [
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80",
    ],
    seller: {
      id: "s8",
      name: "Simone Charles",
      avatar: "https://i.pravatar.cc/80?img=44",
      joinedDate: "2023-02-14",
      rating: 4.8,
      reviewCount: 29,
      location: "Diego Martin",
      verified: true,
      isPro: false,
    },
    createdAt: "2026-06-03",
    featured: false,
    tier: "free",
    tags: ["dress", "fashion", "local", "women"],
    negotiable: false,
    commentCount: 0,
  },
  {
    id: "9",
    title: "Garden Set – 4-Seater with Umbrella",
    description:
      "Powder-coated steel outdoor dining set. 4 chairs and one round table with parasol stand (umbrella included). Weather-resistant cushions. Slight surface rust on one chair leg, easily touched up. Moving sale.",
    price: 1800,
    currency: "TTD",
    category: "Home & Garden",
    condition: "Good",
    location: "Fyzabad",
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80",
    ],
    seller: {
      id: "s9",
      name: "Gregory Hosein",
      avatar: "https://i.pravatar.cc/80?img=22",
      joinedDate: "2021-04-07",
      rating: 4.3,
      reviewCount: 11,
      location: "Fyzabad",
      verified: false,
      isPro: false,
    },
    createdAt: "2026-05-30",
    featured: false,
    tier: "free",
    tags: ["garden", "furniture", "outdoor", "patio"],
    negotiable: true,
    commentCount: 0,
  },
  {
    id: "10",
    title: "Freelance Web Design & Development",
    description:
      "Professional web design and full-stack development for small businesses, restaurants, and freelancers. Next.js, WordPress, and e-commerce (Shopify) specialist. Portfolio available. Response within 24 hours.",
    price: 2500,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "Port of Spain",
    images: [
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80",
    ],
    seller: {
      id: "s10",
      name: "Nadia Persad",
      avatar: "https://i.pravatar.cc/80?img=36",
      joinedDate: "2023-09-01",
      rating: 4.9,
      reviewCount: 52,
      location: "Port of Spain",
      verified: true,
      isPro: true,
      businessName: "Nadia Digital Studio",
      bio: "Full-stack developer and designer helping T&T businesses get online. Portfolio: nadiadigital.tt",
      banner: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
      listingCount: 3,
    },
    createdAt: "2026-06-10",
    featured: true,
    tier: "premium",
    tags: ["web", "design", "freelance", "nextjs"],
    negotiable: true,
    commentCount: 9,
  },
  {
    id: "11",
    title: "2023 Honda CR-V Turbo – Showroom Condition",
    description:
      "Brand new 2023 Honda CR-V 1.5T EX-L. Fully loaded — panoramic sunroof, leather seats, Honda Sensing suite, wireless CarPlay. Available in Pearl White and Lunar Silver. Finance options available. Test drives by appointment.",
    price: 320000,
    currency: "TTD",
    category: "Vehicles",
    condition: "New",
    location: "Chaguanas",
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
      "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80",
    ],
    seller: {
      id: "s11",
      name: "Ryan Mohammed",
      avatar: "https://i.pravatar.cc/80?img=13",
      joinedDate: "2018-04-01",
      rating: 4.9,
      reviewCount: 210,
      location: "Chaguanas",
      verified: true,
      isPro: true,
      businessName: "Caribbean Auto Sales",
      bio: "Trinidad's largest authorised Honda & Toyota dealership. Over 500 vehicles in stock. Finance, insurance, and trade-in available.",
      banner: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=80",
      listingCount: 24,
    },
    createdAt: "2026-06-09",
    featured: true,
    tier: "premium",
    tags: ["honda", "suv", "new", "finance"],
    negotiable: false,
    commentCount: 3,
  },
  {
    id: "12",
    title: "2022 Toyota Hilux SR5 – Double Cab",
    description:
      "2022 Toyota Hilux SR5 double cab, 2.8L diesel automatic. Bull bar, tow bar, bed liner. Low mileage fleet vehicle. Ideal for business or heavy-duty use. Service history available. Finance from 4.9% APR.",
    price: 295000,
    currency: "TTD",
    category: "Vehicles",
    condition: "Like New",
    location: "Chaguanas",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    seller: {
      id: "s11",
      name: "Ryan Mohammed",
      avatar: "https://i.pravatar.cc/80?img=13",
      joinedDate: "2018-04-01",
      rating: 4.9,
      reviewCount: 210,
      location: "Chaguanas",
      verified: true,
      isPro: true,
      businessName: "Caribbean Auto Sales",
      bio: "Trinidad's largest authorised Honda & Toyota dealership. Over 500 vehicles in stock. Finance, insurance, and trade-in available.",
      banner: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=80",
      listingCount: 24,
    },
    createdAt: "2026-06-07",
    featured: true,
    tier: "premium",
    tags: ["toyota", "hilux", "diesel", "pickup"],
    negotiable: false,
    commentCount: 1,
  },
  {
    id: "13",
    title: "Luxury 4-Bedroom Penthouse – St. Clair",
    description:
      "Exceptional penthouse on the 12th floor in the heart of St. Clair. 4 bedrooms, 4.5 bathrooms, chef's kitchen, private rooftop terrace, 2 covered parking spaces. 24-hour security and concierge. Available for sale or long-term lease.",
    price: 4500000,
    currency: "TTD",
    category: "Real Estate",
    condition: "New",
    location: "St. Clair, Port of Spain",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    ],
    seller: {
      id: "s12",
      name: "Sandra Ferreira",
      avatar: "https://i.pravatar.cc/80?img=46",
      joinedDate: "2015-07-12",
      rating: 4.8,
      reviewCount: 97,
      location: "Port of Spain",
      verified: true,
      isPro: true,
      businessName: "Prime Properties T&T",
      bio: "Award-winning real estate brokerage specialising in luxury residential and commercial properties across Trinidad & Tobago since 2010.",
      banner: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80",
      listingCount: 18,
    },
    createdAt: "2026-06-05",
    featured: true,
    tier: "premium",
    tags: ["penthouse", "luxury", "st. clair", "sale"],
    negotiable: true,
    commentCount: 5,
  },
  {
    id: "14",
    title: "Commercial Office Space – Port of Spain CBD",
    description:
      "2,400 sq ft open-plan office on the 6th floor of a modern building on Independence Square. Air-conditioned, high-speed fibre, backup generator, 8 dedicated parking spaces. Ideal for law firms, financial services, or tech companies.",
    price: 22000,
    currency: "TTD",
    category: "Real Estate",
    condition: "New",
    location: "Independence Square, Port of Spain",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    ],
    seller: {
      id: "s12",
      name: "Sandra Ferreira",
      avatar: "https://i.pravatar.cc/80?img=46",
      joinedDate: "2015-07-12",
      rating: 4.8,
      reviewCount: 97,
      location: "Port of Spain",
      verified: true,
      isPro: true,
      businessName: "Prime Properties T&T",
      bio: "Award-winning real estate brokerage specialising in luxury residential and commercial properties across Trinidad & Tobago since 2010.",
      banner: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80",
      listingCount: 18,
    },
    createdAt: "2026-06-03",
    featured: true,
    tier: "premium",
    tags: ["office", "commercial", "port of spain", "lease"],
    negotiable: true,
    commentCount: 2,
  },
  {
    id: "15",
    title: "Corporate Fleet Cleaning & Maintenance",
    description:
      "Full-service vehicle detailing and fleet maintenance for corporate clients. We handle everything from weekly washes to full paint correction, ceramic coating, and scheduled servicing. Contracts available for 5+ vehicles. Serving Port of Spain, San Fernando, and Chaguanas.",
    price: 8500,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "San Fernando",
    images: [
      "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=800&q=80",
    ],
    seller: {
      id: "s13",
      name: "Damien Jackman",
      avatar: "https://i.pravatar.cc/80?img=17",
      joinedDate: "2017-03-22",
      rating: 4.7,
      reviewCount: 163,
      location: "San Fernando",
      verified: true,
      isPro: true,
      businessName: "AutoShine Pro T&T",
      bio: "Trinidad's leading corporate fleet detailing and vehicle maintenance company. ISO-certified. Serving over 80 corporate clients island-wide.",
      banner: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=1200&q=80",
      listingCount: 6,
    },
    createdAt: "2026-06-08",
    featured: true,
    tier: "premium",
    tags: ["fleet", "cleaning", "corporate", "detailing"],
    negotiable: true,
    commentCount: 4,
  },
  // ── Graphic House ──────────────────────────────────────────────────────────
  {
    id: "17",
    title: "Commercial Printing Services – Brochures, Flyers & Business Cards",
    description:
      "Full-service commercial printing for businesses across Trinidad & Tobago. We produce high-quality brochures, flyers, business cards, catalogues, pull-up banners, and stationery. Offset and digital printing available. Fast turnaround — 24-hour rush service on most products. Corporate accounts and bulk pricing available. Serving T&T since 1977.",
    price: 500,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "Port of Spain",
    images: [
      "/graphic-house-logo.png",
      "/gh-client-churchs.jpg",
    ],
    seller: {
      id: "s14",
      name: "Graphic House Ltd",
      avatar: "/graphic-house-logo.png",
      joinedDate: "2018-06-01",
      rating: 4.9,
      reviewCount: 312,
      location: "Port of Spain",
      verified: true,
      isPro: true,
      businessName: "Graphic House",
      bio: "Trinidad & Tobago's leading print and promotional products company since 1977. From business cards to full corporate campaigns — we bring your brand to life.",
      banner: "/graphic-house-logo.png",
      listingCount: 3,
    },
    createdAt: "2026-06-10",
    featured: true,
    tier: "premium",
    tags: ["printing", "brochures", "business cards", "flyers", "corporate"],
    negotiable: false,
    commentCount: 6,
  },
  {
    id: "18",
    title: "Promotional Merchandise & Branded Corporate Gifts",
    description:
      "Elevate your brand with custom promotional merchandise from Graphic House. We supply and brand pens, mugs, USB drives, tote bags, notebooks, apparel, and hundreds of other corporate gift items. Ideal for trade shows, staff gifts, client appreciation, and event giveaways. Minimum orders apply. Samples available on request.",
    price: 1200,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "Port of Spain",
    images: [
      "/gh-client-happyplanet.jpg",
      "/gh-client-bmobile.jpg",
    ],
    seller: {
      id: "s14",
      name: "Graphic House Ltd",
      avatar: "/graphic-house-logo.png",
      joinedDate: "2018-06-01",
      rating: 4.9,
      reviewCount: 312,
      location: "Port of Spain",
      verified: true,
      isPro: true,
      businessName: "Graphic House",
      bio: "Trinidad & Tobago's leading print and promotional products company since 1977. From business cards to full corporate campaigns — we bring your brand to life.",
      banner: "/graphic-house-logo.png",
      listingCount: 3,
    },
    createdAt: "2026-06-09",
    featured: true,
    tier: "premium",
    tags: ["promotional", "merchandise", "branded", "corporate gifts", "apparel"],
    negotiable: false,
    commentCount: 3,
  },
  {
    id: "19",
    title: "Signage, Large Format & Exhibition Display Printing",
    description:
      "Custom signage and large format printing for retail, corporate, and exhibition environments. We produce vinyl banners, acrylic signs, foam board displays, vehicle wraps, window graphics, outdoor billboards, and full exhibition stand systems. Weather-resistant inks and premium substrates. Installation service available island-wide.",
    price: 2500,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "Port of Spain",
    images: [
      "/gh-client-bmobile.jpg",
      "/gh-client-churchs.jpg",
      "/gh-client-happyplanet.jpg",
    ],
    seller: {
      id: "s14",
      name: "Graphic House Ltd",
      avatar: "/graphic-house-logo.png",
      joinedDate: "2018-06-01",
      rating: 4.9,
      reviewCount: 312,
      location: "Port of Spain",
      verified: true,
      isPro: true,
      businessName: "Graphic House",
      bio: "Trinidad & Tobago's leading print and promotional products company since 1977. From business cards to full corporate campaigns — we bring your brand to life.",
      banner: "/graphic-house-logo.png",
      listingCount: 3,
    },
    createdAt: "2026-06-08",
    featured: true,
    tier: "premium",
    tags: ["signage", "banners", "exhibition", "large format", "vehicle wrap"],
    negotiable: true,
    commentCount: 2,
  },
  // ── (end Graphic House) ────────────────────────────────────────────────────
  {
    id: "16",
    title: "Commercial Security & Surveillance Installation",
    description:
      "Full CCTV, access control, and alarm system installation for offices, warehouses, and retail locations. We supply, install, and maintain Hikvision and Dahua systems. 24/7 monitoring packages available. Over 300 commercial installations across T&T.",
    price: 15000,
    currency: "TTD",
    category: "Services",
    condition: "New",
    location: "Port of Spain",
    images: [
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80",
    ],
    seller: {
      id: "s13",
      name: "Damien Jackman",
      avatar: "https://i.pravatar.cc/80?img=17",
      joinedDate: "2017-03-22",
      rating: 4.7,
      reviewCount: 163,
      location: "San Fernando",
      verified: true,
      isPro: true,
      businessName: "AutoShine Pro T&T",
      bio: "Trinidad's leading corporate fleet detailing and vehicle maintenance company. ISO-certified. Serving over 80 corporate clients island-wide.",
      banner: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=1200&q=80",
      listingCount: 6,
    },
    createdAt: "2026-06-06",
    featured: false,
    tier: "featured",
    tags: ["cctv", "security", "surveillance", "commercial"],
    negotiable: true,
    commentCount: 0,
  },
];

export const inquiries: Inquiry[] = [
  {
    id: "i1",
    listingId: "1",
    listingTitle: "2019 Toyota Corolla – Low Mileage",
    buyerName: "Jason Williams",
    buyerEmail: "jason.w@email.com",
    message: "Hi, is the car still available? Can we arrange a test drive this weekend?",
    createdAt: "2026-06-10",
    read: false,
  },
  {
    id: "i2",
    listingId: "2",
    listingTitle: "MacBook Pro 14\" M3 – Space Grey",
    buyerName: "Rhonda Baptiste",
    buyerEmail: "rhonda.b@email.com",
    message: "Would you take $9,500 TTD? I can pay cash and pick up today.",
    createdAt: "2026-06-09",
    read: true,
  },
  {
    id: "i3",
    listingId: "6",
    listingTitle: "iPhone 15 Pro – 256GB Natural Titanium",
    buyerName: "David Ramkissoon",
    buyerEmail: "david.r@email.com",
    message: "Does this come with a warranty? Also, is the IMEI clean?",
    createdAt: "2026-06-11",
    read: false,
  },
];

export const comments: Comment[] = [
  {
    id: "c1",
    listingId: "1",
    authorName: "Jason Williams",
    authorAvatar: "https://i.pravatar.cc/80?img=3",
    text: "Is this still available? Looks in great condition.",
    createdAt: "2026-06-08T10:22:00Z",
    replies: [
      {
        id: "r1",
        authorName: "Marcus Phillip",
        authorAvatar: "https://i.pravatar.cc/80?img=11",
        text: "Yes still available! Feel free to WhatsApp me to arrange a viewing.",
        createdAt: "2026-06-08T11:05:00Z",
      },
    ],
  },
  {
    id: "c2",
    listingId: "1",
    authorName: "Tricia Ramsaran",
    authorAvatar: "https://i.pravatar.cc/80?img=29",
    text: "What's the mileage on it? And has it ever been in an accident?",
    createdAt: "2026-06-09T14:30:00Z",
    replies: [
      {
        id: "r2",
        authorName: "Marcus Phillip",
        authorAvatar: "https://i.pravatar.cc/80?img=11",
        text: "63,000 km and no accidents. Full service history available.",
        createdAt: "2026-06-09T15:10:00Z",
      },
    ],
  },
  {
    id: "c3",
    listingId: "1",
    authorName: "Kevin Sookdeo",
    authorAvatar: "https://i.pravatar.cc/80?img=15",
    text: "Very reasonable price for a 2019 Corolla. These run forever.",
    createdAt: "2026-06-10T08:00:00Z",
    replies: [],
  },
  {
    id: "c4",
    listingId: "1",
    authorName: "Sandra Ali",
    authorAvatar: "https://i.pravatar.cc/80?img=9",
    text: "Does it have the original floor mats? Also, are the tints legal?",
    createdAt: "2026-06-11T09:45:00Z",
    replies: [],
  },
  {
    id: "c5",
    listingId: "2",
    authorName: "Rohan Maharaj",
    authorAvatar: "https://i.pravatar.cc/80?img=7",
    text: "Which exact M3 variant — base, Pro or Max chip?",
    createdAt: "2026-06-02T12:00:00Z",
    replies: [
      {
        id: "r3",
        authorName: "Priya Ramlal",
        authorAvatar: "https://i.pravatar.cc/80?img=5",
        text: "Base M3 chip, 16GB unified memory, 512GB SSD. Not Pro or Max.",
        createdAt: "2026-06-02T12:45:00Z",
      },
    ],
  },
  {
    id: "c6",
    listingId: "10",
    authorName: "Anil Seepersad",
    authorAvatar: "https://i.pravatar.cc/80?img=20",
    text: "Do you do e-commerce sites for small restaurants? Looking for something with online ordering.",
    createdAt: "2026-06-11T10:00:00Z",
    replies: [
      {
        id: "r4",
        authorName: "Nadia Persad",
        authorAvatar: "https://i.pravatar.cc/80?img=36",
        text: "Absolutely! I specialize in restaurant sites with online ordering. Send me a message and we can discuss your needs.",
        createdAt: "2026-06-11T10:30:00Z",
      },
    ],
  },
];

export const conversations: Conversation[] = [
  {
    id: "conv1",
    participantId: "s2",
    participantName: "Priya Ramlal",
    participantAvatar: "https://i.pravatar.cc/80?img=5",
    listingId: "2",
    listingTitle: "MacBook Pro 14\" M3 – Space Grey",
    listingImage: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80",
    listingPrice: "TTD 9,800",
    messages: [
      {
        id: "m1",
        senderId: "me",
        senderName: "You",
        senderAvatar: "https://i.pravatar.cc/80?img=11",
        text: "Hi Priya, is the MacBook still available?",
        createdAt: "2026-06-09T14:00:00Z",
      },
      {
        id: "m2",
        senderId: "s2",
        senderName: "Priya Ramlal",
        senderAvatar: "https://i.pravatar.cc/80?img=5",
        text: "Yes it is! Still in perfect condition. Are you in San Fernando or can you come down?",
        createdAt: "2026-06-09T14:15:00Z",
      },
      {
        id: "m3",
        senderId: "me",
        senderName: "You",
        senderAvatar: "https://i.pravatar.cc/80?img=11",
        text: "I can come to San Fernando. Would TT$9,500 be okay?",
        createdAt: "2026-06-09T14:30:00Z",
      },
      {
        id: "m4",
        senderId: "s2",
        senderName: "Priya Ramlal",
        senderAvatar: "https://i.pravatar.cc/80?img=5",
        text: "Price is firm at 9,800 since it still has AppleCare+. Can do Saturday morning if that works?",
        createdAt: "2026-06-09T14:45:00Z",
      },
    ],
    unread: 1,
  },
  {
    id: "conv2",
    participantId: "s4",
    participantName: "Cheryl James",
    participantAvatar: "https://i.pravatar.cc/80?img=32",
    listingId: "4",
    listingTitle: "Homemade Black Cake – Order for Events",
    listingImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80",
    listingPrice: "TTD 350",
    messages: [
      {
        id: "m5",
        senderId: "me",
        senderName: "You",
        senderAvatar: "https://i.pravatar.cc/80?img=11",
        text: "Hi! I need a black cake for a wedding on July 12th. Is that enough notice?",
        createdAt: "2026-06-10T09:00:00Z",
      },
      {
        id: "m6",
        senderId: "s4",
        senderName: "Cheryl James",
        senderAvatar: "https://i.pravatar.cc/80?img=32",
        text: "Yes, that's perfect timing! What size are you looking for and how many tiers?",
        createdAt: "2026-06-10T09:20:00Z",
      },
    ],
    unread: 1,
  },
  {
    id: "conv3",
    participantId: "s10",
    participantName: "Nadia Persad",
    participantAvatar: "https://i.pravatar.cc/80?img=36",
    listingId: "10",
    listingTitle: "Freelance Web Design & Development",
    listingImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&q=80",
    listingPrice: "TTD 2,500",
    messages: [
      {
        id: "m7",
        senderId: "me",
        senderName: "You",
        senderAvatar: "https://i.pravatar.cc/80?img=11",
        text: "Hey Nadia, I saw your listing. We need a website for our catering business. Do you do those?",
        createdAt: "2026-06-11T08:00:00Z",
      },
      {
        id: "m8",
        senderId: "s10",
        senderName: "Nadia Persad",
        senderAvatar: "https://i.pravatar.cc/80?img=36",
        text: "Absolutely! Catering sites are a specialty — menu pages, gallery, booking form, everything. Let's hop on a quick call.",
        createdAt: "2026-06-11T08:30:00Z",
      },
      {
        id: "m9",
        senderId: "me",
        senderName: "You",
        senderAvatar: "https://i.pravatar.cc/80?img=11",
        text: "Perfect. Are you free Thursday afternoon?",
        createdAt: "2026-06-11T08:45:00Z",
      },
    ],
    unread: 0,
  },
];

export const walletTransactions: WalletTransaction[] = [
  { id: "w1", type: "topup", amount: 100, description: "Top-up via credit card", date: "2026-06-01" },
  { id: "w2", type: "spend", amount: 50, description: "Featured listing – Toyota Corolla (1 month)", date: "2026-06-02" },
  { id: "w3", type: "topup", amount: 150, description: "Top-up via credit card", date: "2026-06-08" },
  { id: "w4", type: "spend", amount: 120, description: "Premium listing – Freelance Web Design (1 month)", date: "2026-06-10" },
];

export const walletBalance = 95;

export const categories = [
  { name: "Electronics", icon: "💻", count: 2 },
  { name: "Vehicles", icon: "🚗", count: 1 },
  { name: "Real Estate", icon: "🏠", count: 1 },
  { name: "Fashion", icon: "👗", count: 1 },
  { name: "Food & Beverage", icon: "🍰", count: 1 },
  { name: "Services", icon: "🔧", count: 2 },
  { name: "Home & Garden", icon: "🪴", count: 1 },
  { name: "Sports & Outdoors", icon: "🏄", count: 1 },
];
